version: "3.3"
services:
  level3:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 33333:80

  flag:
    build: ./flag
    restart: unless-stopped

  api:
    build: ./api
    restart: unless-stopped
