version: "3.6"
services:
  level4:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 33334:80

  flag:
    build: ./flag
    restart: unless-stopped

  api:
    build: ./api
    restart: unless-stopped